services:
  db:
    image: postgres:16
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  gateway:
    build: 
      context: ./gateway
      dockerfile: Dockerfile
    restart: always
    env_file:
      - .env
    ports:
      - "80:80"
    depends_on:
      - db
      - web
      - generate

  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    restart: always
    env_file:
      - .env
    ports:
      - "3000:3000"
    depends_on:
      - db

  generate:
    build:
      context: ./generate
      dockerfile: Dockerfile
    restart: always
    env_file:
      - .env
    ports:
      - "3001:3001"
    depends_on:
      - db

volumes:
  pgdata: